# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "194a5c6bd1568aafe7c4edd70301f8fb"
name = "Majik"
handle = "Majik"
application_url = "https://dicke-person-mighty-hispanic.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-bc4fc407.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_metaobject_definitions,read_metaobjects,read_products,write_content,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://dicke-person-mighty-hispanic.trycloudflare.com/auth/callback",
  "https://dicke-person-mighty-hispanic.trycloudflare.com/auth/shopify/callback",
  "https://dicke-person-mighty-hispanic.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false
