import { useState } from "react";
import { Page, Layout, Card, Button, Text, BlockStack, Box, Link, InlineStack, List} from "@shopify/polaris";
import { TitleBar } from "@shopify/app-bridge-react";

export default function Index() {
  const [namespace, setNamespace] = useState("cartesian");

  const toggleNamespace = () => {
    setNamespace(namespace === "cartesian" ? "global" : "cartesian");
  };

  const metafieldCode = namespace === "cartesian" ? `
    <div class="metafields-container">  
      {% assign product_namespace = "cartesian" %}
      {% for metafield in product.metafields[product_namespace] %}
        {% if metafield[1].value != blank %}
          <p><strong>{{ metafield[0] | replace: '_', ' ' | capitalize }}:</strong> {{ metafield[1].value }}</p>
        {% endif %}
      {% endfor %}
    </div>

    <script>
      console.log({{ product| json}});
    </script>` : `
    <!-- Global namespace metafields example -->
    <div class="metafields-container">
      <!-- Add global namespace metafields here -->
      <p>Example Global Namespace Metafields Display</p>
    </div>`;

  return (
    <Page title="Welcome to Majik by Plotch.ai">
      <TitleBar title="Majik - Enhance Metadata with AI" />
      <BlockStack gap="500">
        <Layout>
          <Layout.Section>
            <Card title="Enhance Your Metadata with Majik" sectioned>
              <Text as="h1" variant="headingLg">
                Revolutionize Your Shopify Metadata Management
              </Text>
              <Text as="p" variant="bodyMd">
                Majik uses AI-powered metadata generation from Plotch.ai to provide you with the best, most accurate product metadata in the market. Improve product visibility and organization in your Shopify store with high-quality metadata generation.
              </Text>
              <Button primary onClick={() => alert("Let's get started!")}>
                Get Started
              </Button>
            </Card>

            <Card title="Features" sectioned>
              <BlockStack gap="300">
                <Text variant="headingMd">Generate Metadata</Text>
                <Text as="p" variant="bodyMd">
                  Select products from your store, and Majik will generate metadata for you at just ₹1 per product. Our AI ensures the most accurate and relevant metadata. Once you place the order, the request is processed immediately.
                </Text>

                <Text variant="headingMd">Review Metadata</Text>
                <Text as="p" variant="bodyMd">
                  View and manage your metadata generation requests in real-time. Apply the metadata to your products at any time from the Review page. Process, review, and apply effortlessly.
                </Text>

                <Text variant="headingMd">Manage Product Metadata</Text>
                <Text as="p" variant="bodyMd">
                  Get an overview of all your product metadata. Use the MetaProducts page to create new metafields, update existing ones, or delete unwanted ones. The 'cartesian' namespace ensures that metadata created here is consistent and easy to manage.
                </Text>
              </BlockStack>
            </Card>

            <Card title="Display Metadata in Your Storefront" sectioned>
              <Text as="p" variant="bodyMd">
                Use the following code to display the metafields generated by Majik on your storefront:
              </Text>

              <Button onClick={toggleNamespace}>
                Show {namespace === "cartesian" ? "Global" : "Cartesian"} Namespace
              </Button>

              <Box padding="400" background="bg-surface-active" borderWidth="025" borderRadius="200" borderColor="border" overflowX="scroll">
                <pre style={{ margin: 0 }}>
                  <code>{metafieldCode}</code>
                </pre>
              </Box>

              <Text as="p" variant="bodyMd">
                Simply paste this code into your Shopify theme to display product metafields generated using Majik.
              </Text>
            </Card>
          </Layout.Section>

          <Layout.Section secondary>
            <Card title="Why Choose Majik?" sectioned>
              <InlineStack gap="300" align="center">
                <Box>
                  <Text variant="headingMd">AI-Powered Accuracy</Text>
                  <Text variant="bodyMd">
                    Majik, powered by Plotch.ai, ensures the highest-quality metadata using cutting-edge AI technology. Your store deserves nothing less.
                  </Text>
                </Box>
                <Box>
                  <Text variant="headingMd">Real-Time Updates</Text>
                  <Text variant="bodyMd">
                    Every change you make to your metadata is reflected in real-time, giving you full control over your Shopify store.
                  </Text>
                </Box>
                <Box>
                  <Text variant="headingMd">Affordable</Text>
                  <Text variant="bodyMd">
                    Generate accurate product metadata for just ₹1 per product, saving you both time and money.
                  </Text>
                </Box>
              </InlineStack>
            </Card>

            <Card title="Next Steps" sectioned>
              <List type="bullet">
                <List.Item>
                  Visit the <Link url="/generate">Generate Page</Link> to start creating high-quality metadata.
                </List.Item>
                <List.Item>
                  Track your metadata requests in real-time on the <Link url="/review">Review Page</Link>.
                </List.Item>
                <List.Item>
                  Manage and edit existing metadata from the <Link url="/metaproducts">MetaProducts Page</Link>.
                </List.Item>
              </List>
            </Card>
          </Layout.Section>
        </Layout>
      </BlockStack>
    </Page>
  );
}
